import { useNavigate } from 'react-router-dom';

const Sparkles = (props) => (
  <svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="m12 3-1.912 5.813a2 2 0 0 1-1.275 1.275L3 12l5.813 1.912a2 2 0 0 1 1.275 1.275L12 21l1.912-5.813a2 2 0 0 1 1.275-1.275L21 12l-5.813-1.912a2 2 0 0 1-1.275-1.275L12 3Z" />
    <path d="M5 3v4" />
    <path d="M19 17v4" />
    <path d="M3 5h4" />
    <path d="M17 19h4" />
  </svg>
);

const MapPin = (props) => (
  <svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z" />
    <circle cx="12" cy="10" r="3" />
  </svg>
);

const Calendar = (props) => (
  <svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M8 2v4" />
    <path d="M16 2v4" />
    <rect width="18" height="18" x="3" y="4" rx="2" />
    <path d="M3 10h18" />
  </svg>
);

const Compass = (props) => (
  <svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <circle cx="12" cy="12" r="10" />
    <polygon points="16.24 7.76 14.12 14.12 7.76 16.24 9.88 9.88 16.24 7.76" />
  </svg>
);

const Plane = (props) => (
  <svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M17.8 19.2 16 11l3.5-3.5C21 6 21.5 4 21 3c-1-.5-3 0-4.5 1.5L13 8 4.8 6.2c-.5-.1-.9.1-1.1.5l-.3.5c-.2.5-.1 1 .3 1.3L9 12l-2 3H4l-1 1 3 2 2 3 1-1v-3l3-2 3.5 5.3c.3.4.8.5 1.3.3l.5-.2c.4-.3.6-.7.5-1.2z" />
  </svg>
);

const Heart = (props) => (
  <svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z" />
  </svg>
);

const Zap = (props) => (
  <svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2" />
  </svg>
);

const Users = (props) => (
  <svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
    <circle cx="9" cy="7" r="4" />
    <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
    <path d="M16 3.13a4 4 0 0 1 0 7.75" />
  </svg>
);

const AnimatedBackground = () => (
  <div className="fixed inset-0 -z-10 overflow-hidden pointer-events-none">
    <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-blue-500/10 rounded-full blur-3xl animate-float" />
    <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-purple-500/10 rounded-full blur-3xl animate-float-delayed" />
    <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-pink-500/5 rounded-full blur-3xl animate-pulse" />
  </div>
);

const HomePage = () => {
  const navigate = useNavigate();
  
  const handleCreateNew = () => {
    localStorage.removeItem('itineraryData');
    
    window.dispatchEvent(new Event('itineraryUpdated'));
    
    navigate('/form');
  };

  const features = [
    {
      icon: <Sparkles className="w-8 h-8" />,
      title: "AI-Powered Planning",
      description: "Get personalized itineraries generated by advanced AI based on your preferences",
      color: "blue"
    },
    {
      icon: <MapPin className="w-8 h-8" />,
      title: "Day-by-Day Details",
      description: "Complete breakdown of activities, places to visit, and local food recommendations",
      color: "purple"
    },
    {
      icon: <Calendar className="w-8 h-8" />,
      title: "Flexible Scheduling",
      description: "Choose your travel dates, duration, and interests for a customized experience",
      color: "pink"
    },
    {
      icon: <Heart className="w-8 h-8" />,
      title: "Curated Destinations",
      description: "Explore hand-picked travel suggestions with detailed highlights and tips",
      color: "orange"
    }
  ];

  const stats = [
    { number: "1000+", label: "Destinations", icon: <MapPin className="w-6 h-6" /> },
    { number: "50K+", label: "Happy Travelers", icon: <Users className="w-6 h-6" /> },
    { number: "AI", label: "Powered", icon: <Zap className="w-6 h-6" /> },
  ];

  return (
    <div className="min-h-screen relative bg-gradient-to-b from-slate-950 via-slate-900 to-slate-950">
      <AnimatedBackground />
      
      <div className="relative z-10">
        <section className="min-h-screen flex items-center justify-center px-4 md:px-6 py-20">
          <div className="max-w-6xl mx-auto text-center space-y-12">
            <div className="inline-flex items-center gap-3 backdrop-blur-xl bg-white/5 px-6 py-3 rounded-full border border-white/10 shadow-lg hover:scale-105 transition-transform duration-300 animate-fade-in">
              <Plane className="w-5 h-5 text-blue-400 animate-pulse" />
              <span className="text-sm font-semibold text-slate-300 uppercase tracking-wider">
                Your Personal AI Travel Guide
              </span>
            </div>

            <div className="space-y-6 animate-slide-in-up">
              <h1 className="text-6xl md:text-8xl font-black leading-tight">
                <span className="bg-gradient-to-r from-blue-400 via-purple-400 to-pink-400 bg-clip-text text-transparent animate-gradient block mb-4">
                  Plan Your Perfect
                </span>
                <span className="text-white block">
                  Adventure
                </span>
              </h1>
              
              <p className="text-xl md:text-2xl text-slate-400 max-w-3xl mx-auto leading-relaxed">
                Let AI craft personalized travel itineraries tailored to your interests, or explore our curated destination recommendations
              </p>
            </div>

            <div className="flex flex-col sm:flex-row gap-6 justify-center items-center animate-fade-in" style={{ animationDelay: '0.3s' }}>
             <button
      onClick={handleCreateNew} 
      className="group relative px-10 py-5 text-lg font-bold text-white backdrop-blur-xl bg-gradient-to-r from-blue-600 via-purple-600 to-pink-600 rounded-2xl overflow-hidden shadow-2xl hover:shadow-purple-500/50 transition-all duration-300 hover:scale-105 w-full sm:w-auto"
    >
      <span className="relative z-10 flex items-center justify-center gap-3">
        <Sparkles className="w-6 h-6" />
        Generate Itinerary
      </span>
      <div className="absolute inset-0 bg-gradient-to-r from-pink-600 via-purple-600 to-blue-600 opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
    </button>

              <button
                onClick={() => navigate('/suggested-trips')}
                className="group px-10 py-5 text-lg font-bold text-blue-400 backdrop-blur-xl bg-white/5 border-2 border-blue-500/40 rounded-2xl hover:bg-blue-500/10 hover:border-blue-400/60 transition-all duration-300 hover:scale-105 shadow-lg w-full sm:w-auto"
              >
                <span className="flex items-center justify-center gap-3">
                  <Compass className="w-6 h-6 group-hover:rotate-45 transition-transform duration-300" />
                  Explore Destinations
                </span>
              </button>
            </div>

            {/* Stats */}
            <div className="grid grid-cols-3 gap-6 max-w-3xl mx-auto pt-12 animate-fade-in" style={{ animationDelay: '0.5s' }}>
              {stats.map((stat, index) => (
                <div key={index} className="backdrop-blur-xl bg-white/5 rounded-2xl p-6 border border-white/10 hover:scale-105 transition-transform duration-300">
                  <div className="flex justify-center mb-3 text-blue-400">
                    {stat.icon}
                  </div>
                  <p className="text-3xl font-black text-white mb-1">{stat.number}</p>
                  <p className="text-sm text-slate-400 uppercase tracking-wider">{stat.label}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="px-4 md:px-6 py-24 bg-slate-950/50">
          <div className="max-w-7xl mx-auto">
            <div className="text-center mb-16">
              <div className="inline-block backdrop-blur-xl bg-white/5 px-6 py-2 rounded-full border border-white/10 mb-6">
                <p className="text-sm font-semibold text-purple-400 uppercase tracking-wider">
                  Why Choose Us
                </p>
              </div>
              <h2 className="text-4xl md:text-6xl font-black mb-6">
                <span className="bg-gradient-to-r from-blue-400 to-purple-400 bg-clip-text text-transparent">
                  Travel Made Simple
                </span>
              </h2>
              <p className="text-slate-400 text-xl max-w-2xl mx-auto">
                Everything you need to plan the perfect trip, powered by artificial intelligence
              </p>
            </div>

            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
              {features.map((feature, index) => (
                <div
                  key={index}
                  className="group backdrop-blur-xl bg-gradient-to-br from-white/10 to-white/5 rounded-3xl p-8 border border-white/10 hover:border-purple-500/50 transition-all duration-500 hover:scale-105 animate-slide-in-up"
                  style={{ animationDelay: `${index * 0.1}s` }}
                >
                  <div className={`w-16 h-16 rounded-2xl bg-gradient-to-br from-${feature.color}-500 to-${feature.color}-600 flex items-center justify-center shadow-lg shadow-${feature.color}-500/50 group-hover:scale-110 transition-transform duration-300 mb-6 text-white`}>
                    {feature.icon}
                  </div>
                  <h3 className="text-xl font-bold text-white mb-3">{feature.title}</h3>
                  <p className="text-slate-400 leading-relaxed">{feature.description}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="px-4 md:px-6 py-24">
          <div className="max-w-4xl mx-auto text-center">
            <div className="backdrop-blur-2xl bg-gradient-to-br from-white/10 to-white/5 rounded-3xl p-12 border border-white/10 shadow-2xl">
              <Sparkles className="w-16 h-16 text-yellow-400 mx-auto mb-6 animate-pulse" />
              <h2 className="text-4xl md:text-5xl font-black text-white mb-6">
                Ready to Start Your Journey?
              </h2>
              <p className="text-slate-400 text-lg mb-8 max-w-2xl mx-auto">
                Whether you want a custom itinerary or curated suggestions, we've got you covered. Start planning your dream trip today!
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <button
                  onClick={() => navigate('/create-itinerary')}
                  className="px-8 py-4 bg-gradient-to-r from-blue-600 to-purple-600 text-white font-bold rounded-2xl hover:scale-105 transition-transform duration-300 shadow-xl hover:shadow-purple-500/50"
                >
                  Get Started Now →
                </button>
                <button
                  onClick={() => navigate('/suggested-trips')}
                  className="px-8 py-4 backdrop-blur-xl bg-white/5 border-2 border-purple-500/40 text-purple-400 font-bold rounded-2xl hover:bg-purple-500/10 transition-all duration-300 hover:scale-105"
                >
                  Browse Destinations
                </button>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
};

export default HomePage;